### ISSUE TITLE
Play restarts App after each request

### ISSUE THREAD

**Issue by papauschek** [jamesward/play-auto-refresh#14]
I just tried to integrate the auto-refresher in a bigger project with some submodules, and noticed that the Play app reloads after each request (reloading all the database plugins and restarting the default akka system, etc.) , even if no changes are made. Is this  behavior intended?

If not, any hints on what could cause this behavior?

The SBT BrowserNotifierPlugin settings are only included in the main project, and the Play app works fine when I exclude them (without unnecessary reloads).

**Comment by mkurz** [comment]
9 years old, IMHO this was a Play bug long time ago. Closing
