### ISSUE TITLE
Can this be used with activator Play projects?

### ISSUE THREAD

**Issue by sejensen** [jamesward/play-auto-refresh#16]
Hi James

I Would really love to get the reload feature to work with our new play (Activator based) project.

It complains in build.scala about the livereload setting:

Build.scala:20: no `: __' annotation allowed here
[error](such annotations are only allowed in arguments to *-parameters)
[error]     com.jamesward.play.BrowserNotifierPlugin.livereload: __,
[error]                                                        ^
[error] one error found
[error](compile:compile) Compilation failed
Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore?

Configuration file is:

import com.ketalo.play.plugins.emberjs.EmberJsKeys
import sbt._

object ApplicationBuild extends Build with EmberJsKeys {

  val appName         = "???"
  val appVersion      = "0.1-SNAPSHOT"

  val appDependencies = Seq(
    "com.google.inject" % "guice" % "3.0",
    "javax.inject" % "javax.inject" % "1",
    "org.reactivemongo" %% "reactivemongo" % "0.10.0",
    "org.reactivemongo" %% "play2-reactivemongo" % "0.10.2",

```
"org.mockito" % "mockito-core" % "1.9.5" % "test"
```

  )

  val main = play.Project(appName, appVersion, appDependencies).settings(
    com.jamesward.play.BrowserNotifierPlugin.livereload: _*,
    emberJsVersion := "1.5.1"
  )

}

Hope that you are able to help, that auto reload increases my productivity!

Kind regards
Steffen

**Comment by nafg** [comment]
@jamesward is this obsolete?

**Comment by jamesward** [comment]
@nafg Are you having issues with `play-auto-refresh` and Activator?

**Comment by nafg** [comment]
@jamesward I don't use Activator

**Comment by jamesward** [comment]
@nafg What is your issue? Are you just suggesting this issue be closed?

**Comment by nafg** [comment]
I was just asking...

**Comment by mkurz** [comment]
play command is dead, activator is dead. Plugin works with sbt, so closing this 9 year old issue.
