### ISSUE TITLE
akka-http

### ISSUE THREAD

**Issue by antonkulaga** [jamesward/play-auto-refresh#32]
It would be nice to get the description about setting it up in akka-http projects.

**Comment by jamesward** [comment]
I don't think that will work at this time.  Sorry.

**Comment by nafg** [comment]
@antonkulaga maybe try https://github.com/lihaoyi/workbench ?

**Comment by mkurz** [comment]
The Plugin is for PLay project obviously. (Also this issue is almost 8 years old now)
