### ISSUE TITLE
Use port passed to run command

### ISSUE THREAD

**Issue by nafg** [jamesward/play-auto-refresh#33]
In Play, you can run the app on a custom port temporarily by entering

```
> run 8080
```

However `play-auto-refresh` still opens the browser to port 9000. The relevant code is here: https://github.com/jamesward/play-auto-refresh/blob/master/src/main/scala/com/jamesward/play/BrowserNotifierPlugin.scala#L41

**Comment by jamesward** [comment]
I don't think there is any way to deal with that since the two plugins are run independently and the only way to know the port is via a shared setting.  So you will have to use the `-Dhttp.port=8080` syntax for your sbt launcher.
