### ISSUE TITLE
Using Maven/SBT file structure not default Play layout

### ISSUE THREAD

**Issue by lashford** [jamesward/play-auto-refresh#35]
Is there a way to specify a different location for the basedirectory, im using Maven layout in my Play project so the directory structure is `/src/main/assets` `/src/main/public` `/src/main/scala` `/src/main/twirl`.

Plugin seems to be expecting all files to watch to be in standard `/app` structure.

Any advice?

**Comment by jamesward** [comment]
I've just released `0.0.15` for Play 2.5 and it *should* fix this.  Can you give it a try and let me know?

**Comment by mkurz** [comment]
This is not an issue anymore IMHO
