### ISSUE TITLE
Add documentation on how to configure the 'Open in editor URL'

### ISSUE THREAD

**Issue by nemoo** [jamesward/play-auto-refresh#36]
I want to use play-auto-refresh in with Intellij. 
It used to work, but now on my new machine I have to set it up anew. I cannot find the information what to use as 'Open in editor URL'  when using Intellij on Windows.

It would be nice to have the most common URLs (linux/windows-eclipse/intellij/atom) as part of the readme + part of the form where the user enters the url, so that people can get started with the plugin easily.

I would be happy to provide a pull request, but first I would need the content.

**Comment by jamesward** [comment]
I think that feature is provided by the Play Framework Tools Chrome Plugin: https://github.com/jamesward/play-framework-chrome-tools

Would you mind filing this issue on that repo?
