### ISSUE TITLE
The auto-refresh doesn't happen with a port different from 9000

### ISSUE THREAD

**Issue by Scipionh** [jamesward/play-auto-refresh#38]
I did try to run my app on port 9002 with sbt "~run 9002". Despite seeing in my console that it has recompiled, my browser doesn't refresh itself. I switch it to port 9000 with a sbt ~run and it did work. Is there something missing in my understanding, or is it a bug/feature ?

**Comment by ssteward54** [comment]
The plugin looks for the `http.port` setting so you could try setting that as a JAVA_OPT.
