### ISSUE TITLE
Custom port as parameter is ignored

### ISSUE THREAD

**Issue by gervaisb** [jamesward/play-auto-refresh#39]
>When executing `~run 8080` from the Sbt console, 
>Then the plugin open the browser on "http://localhost:9000". Instead of "http://localhost:8080"

From the sources, the plugin get the port from the system properties or default to "9000". But here the port is passed as parameter to the _run_ command.

It can be nice to try to retrieve this parameter this option before returning the default port.

**Comment by jamesward** [comment]
What version of Play?

**Comment by gervaisb** [comment]
Play 2.5.10

**Comment by jamesward** [comment]
It looks like I investigated this for #33 and couldn't come up with a way to do this.  Sorry.

**Comment by gervaisb** [comment]
Ok. Sorry for the duplicate.
Le mer. 30 nov. 2016 à 17:15, James Ward <notifications@github.com> a
écrit :
