### ISSUE TITLE
Publish for sbt 1.0?

### ISSUE THREAD

**Issue by rpiaggio** [jamesward/play-auto-refresh#41]
Thank you!

**Comment by jamesward** [comment]
I don't think Play supports sbt 1.0 yet so I'm not sure if I can do this until then.

**Comment by rpiaggio** [comment]
Thank you. You are absolutely right. Play support seems imminent though, let's keep an eye on it.

**Comment by Daxten** [comment]
@jamesward it supports it now :)

**Comment by jamesward** [comment]
Trying to publish `0.0.16` now with sbt 1.0 support.

**Comment by rpiaggio** [comment]
Works great, thank you!
