### ISSUE TITLE
Error after adding the SBT plugin

### ISSUE THREAD

**Issue by neljaj** [jamesward/play-auto-refresh#46]
After adding the sbt plugin to my plugins file (leaving an empty line) I find this error below.  

My build.sbt file have:
resolvers += Resolver.jcenterRepo,

build.properties have:
sbt.version=1.3.10

Really looking forward to using this, so can you please help out.  Thanks

[warn] 
[warn] 	Note: Some unresolved dependencies have extra attributes.  Check that these dependencies exist with the requested attributes.
[warn] 		com.jamesward:play-auto-refresh:0.0.18 (sbtVersion=1.0, scalaVersion=2.12)
[warn] 
[warn] 	Note: Unresolved dependencies path:
[error] sbt.librarymanagement.ResolveException: Error downloading com.jamesward:play-auto-refresh;sbtVersion=1.0;scalaVersion=2.12:0.0.18
[error]   Not found
[error]   Not found
[error]   not found: https://repo1.maven.org/maven2/com/jamesward/play-auto-refresh_2.12_1.0/0.0.18/play-auto-refresh-0.0.18.pom
[error]   not found: /Users/hannesnel/.ivy2/local/com.jamesward/play-auto-refresh/scala_2.12/sbt_1.0/0.0.18/ivys/ivy.xml
[error]   download error: Caught java.io.IOException: Server returned HTTP response code: 502 for URL: https://dl.bintray.com/sbt/sbt-plugin-releases/com.jamesward/play-auto-refresh/scala_2.12/sbt_1.0/0.0.18/ivys/ivy.xml (Server returned HTTP response code: 502 for URL: https://dl.bintray.com/sbt/sbt-plugin-releases/com.jamesward/play-auto-refresh/scala_2.12/sbt_1.0/0.0.18/ivys/ivy.xml) while downloading https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.jamesward/play-auto-refresh/scala_2.12/sbt_1.0/0.0.18/ivys/ivy.xml
[error]   download error: Caught java.io.IOException: Server returned HTTP response code: 502 for URL: https://dl.bintray.com/typesafe/ivy-releases/com.jamesward/play-auto-refresh/scala_2.12/sbt_1.0/0.0.18/ivys/ivy.xml (Server returned HTTP response code: 502 for URL: https://dl.bintray.com/typesafe/ivy-releases/com.jamesward/play-auto-refresh/scala_2.12/sbt_1.0/0.0.18/ivys/ivy.xml) while downloading https://repo.typesafe.com/typesafe/ivy-releases/com.jamesward/play-auto-refresh/scala_2.12/sbt_1.0/0.0.18/ivys/ivy.xml
[error] 	at lmcoursier.CoursierDependencyResolution.unresolvedWarningOrThrow(CoursierDependencyResolution.scala:247)
[error] 	at lmcoursier.CoursierDependencyResolution.$anonfun$update$35(CoursierDependencyResolution.scala:216)
[error] 	at scala.util.Either$LeftProjection.map(Either.scala:573)
[error] 	at lmcoursier.CoursierDependencyResolution.update(CoursierDependencyResolution.scala:216)
[error] 	at sbt.librarymanagement.DependencyResolution.update(DependencyResolution.scala:60)
[error] 	at sbt.internal.LibraryManagement$.resolve$1(LibraryManagement.scala:52)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$12(LibraryManagement.scala:102)
[error] 	at sbt.util.Tracked$.$anonfun$lastOutput$1(Tracked.scala:69)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$20(LibraryManagement.scala:115)
[error] 	at scala.util.control.Exception$Catch.apply(Exception.scala:228)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11(LibraryManagement.scala:115)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11$adapted(LibraryManagement.scala:96)
[error] 	at sbt.util.Tracked$.$anonfun$inputChanged$1(Tracked.scala:150)
[error] 	at sbt.internal.LibraryManagement$.cachedUpdate(LibraryManagement.scala:129)
[error] 	at sbt.Classpaths$.$anonfun$updateTask0$5(Defaults.scala:2950)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:67)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:281)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:19)
[error] 	at sbt.Execute.work(Execute.scala:290)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:281)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[error] 	at java.lang.Thread.run(Thread.java:748)
[error] (update) sbt.librarymanagement.ResolveException: Error downloading com.jamesward:play-auto-refresh;sbtVersion=1.0;scalaVersion=2.12:0.0.18
[error]   Not found
[error]   Not found
[error]   not found: https://repo1.maven.org/maven2/com/jamesward/play-auto-refresh_2.12_1.0/0.0.18/play-auto-refresh-0.0.18.pom
[error]   not found: /Users/hannesnel/.ivy2/local/com.jamesward/play-auto-refresh/scala_2.12/sbt_1.0/0.0.18/ivys/ivy.xml
[error]   download error: Caught java.io.IOException: Server returned HTTP response code: 502 for URL: https://dl.bintray.com/sbt/sbt-plugin-releases/com.jamesward/play-auto-refresh/scala_2.12/sbt_1.0/0.0.18/ivys/ivy.xml (Server returned HTTP response code: 502 for URL: https://dl.bintray.com/sbt/sbt-plugin-releases/com.jamesward/play-auto-refresh/scala_2.12/sbt_1.0/0.0.18/ivys/ivy.xml) while downloading https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.jamesward/play-auto-refresh/scala_2.12/sbt_1.0/0.0.18/ivys/ivy.xml
[error]   download error: Caught java.io.IOException: Server returned HTTP response code: 502 for URL: https://dl.bintray.com/typesafe/ivy-releases/com.jamesward/play-auto-refresh/scala_2.12/sbt_1.0/0.0.18/ivys/ivy.xml (Server returned HTTP response code: 502 for URL: https://dl.bintray.com/typesafe/ivy-releases/com.jamesward/play-auto-refresh/scala_2.12/sbt_1.0/0.0.18/ivys/ivy.xml) while downloading https://repo.typesafe.com/typesafe/ivy-releases/com.jamesward/play-auto-refresh/scala_2.12/sbt_1.0/0.0.18/ivys/ivy.xml
Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore?

**Comment by jamesward** [comment]
It looks like maybe you have a proxy server or something that is blocking access to bintray.  This URL works for me:
https://dl.bintray.com/sbt/sbt-plugin-releases/com.jamesward/play-auto-refresh/scala_2.12/sbt_1.0/0.0.18/ivys/

Does it work for you?

**Comment by neljaj** [comment]
The URL works for me too.  I’ve tried version 0.0.17 and that works fine.

**Comment by jamesward** [comment]
Are you still getting the server 502 responses with 0.0.18 via sbt?

**Comment by neljaj** [comment]
Thanks James, not sure if you changed anything but it is working now.  Thanks for your prompt response!

**Comment by jamesward** [comment]
Good!  Maybe was a temporary network issue on bintray.
