### ISSUE TITLE
Publish to Maven central using sbt-ci-release

### ISSUE THREAD

**Issue by mkurz** [jamesward/play-auto-refresh#47]
The artifacts of play-auto-refresh are only available on repo.scala-sbt.org currently which had a multiple hours outage in April.

@jamesward I see you already published packages to Maven Central so this shouldn't be too hard: https://repo1.maven.org/maven2/com/jamesward/

Can you add the secrets for `com.jamesward` to this repo like you did for webjars-play/?
https://github.com/webjars/webjars-play/pull/101#issuecomment-1495109556
If so, I might come up with a PR to add sbt-ci-release.

Thanks!

**Comment by jamesward** [comment]
Thanks @mkurz! I've added those secrets.

**Comment by mkurz** [comment]
@jamesward Thanks! What do you think about giving me Maintain or Write access to this repo, so I can merge PR's? Maybe also for https://github.com/jamesward/play-framework-chrome-tools which is the chrome plugin?

**Comment by jamesward** [comment]
Invite sent for both.  Thank you!

**Comment by mkurz** [comment]
Thanks! Will work in the repos when I find time.

**Comment by mkurz** [comment]
Done finally:
* https://repo1.maven.org/maven2/com/jamesward/play-auto-refresh_2.12_1.0/
* https://github.com/jamesward/play-auto-refresh/releases/tag/v0.0.19
* https://github.com/jamesward/play-auto-refresh/releases/tag/v0.0.20
