### ISSUE TITLE
Source code for  Play Framework Tools Chrome Extension

### ISSUE THREAD

**Issue by nemoo** [jamesward/play-auto-refresh#48]
Where can I find the source of the  Play Framework Tools Chrome Extension? 
https://chrome.google.com/webstore/detail/play-framework-tools/dchhggpgbommpcjpogaploblnpldbmen

I assume it is related to this plugin? 

Thanks!

**Comment by mkurz** [comment]
I think it's
https://github.com/jamesward/play-framework-chrome-tools

**Comment by mkurz** [comment]
I added the url in the README in
- #49
